export enum AgentInfoType {
    "bank_paying_agent" = "bank_paying_agent" ,
    "bank_paying_subagent" = "bank_paying_subagent",
    "paying_agent" = "paying_agent",
    "paying_subagent" = "paying_subagent",
    "attorney" = "attorney",
    "commission_agent" = "commission_agent",
    "another" = "another",
}

export enum PaymentMethodType {
    "full_prepayment"= "full_prepayment",
    "prepayment" = "prepayment",
    "advance" = "advance",
    "full_payment" = "full_payment",
    "partial_payment" = "partial_payment",
    "credit" = "credit",
    "credit_payment" = "credit_payment",
}

export enum PaymentObjectFFD1_05 {
    "commodity" =  "commodity",
    "excise" = "excise",
    "job" = "job",
    "service" = "service",
    "gambling_bet" = "gambling_bet",
    "gambling_prize" = "gambling_prize",
    "lottery" = "lottery",
    "lottery_prize" = "lottery_prize",
    "intellectual_activity" = "intellectual_activity",
    "payment" = "payment",
    "agent_commission" = "agent_commission",
    "composite" = "composite",
    "award" = "award",
    "another" = "another",
    "property_right" = "property_right",
    "non-operating_gain" = "non-operating_gain",
    "insurance_premium" = "insurance_premium",
    "sales_tax" =  "sales_tax",
    "resort_fee" = "resort_fee",
    "deposit" = "deposit",
    "expense" = "expense",
    "pension_insurance_ip" = "pension_insurance_ip",
    "pension_insurance" = "pension_insurance",
    "medical_insurance_ip" = "medical_insurance_ip",
    "medical_insurance" = "medical_insurance",
    "social_insurance" = "social_insurance",
    "casino_payment" = "casino_payment",
}

export enum VatType {
    "none"= "none",
    "vat0"= "vat0",
    "vat10"= "vat10",
    "vat110"= "vat110",
    "vat20"= "vat20",
    "vat120"= "vat120",
}

export enum PaymentsType {
    "cash",
    "nonCash",
    "prepayment",
    "postPayment",
    "other",
}

export enum TaxSystem {
    "osn" = "osn",
    "usn_income" = "usn_income",
    "usn_income_outcome" = "usn_income_outcome",
    "envd" = "envd",
    "esn" = "esn",
    "patent" = "patent",
}

export enum PaymentObjectFFD1_2 {
    "regularGoods" = 1,
    "exciseGoods" = 2,
    "workPerformed" = 3,
    "serviceProvided" = 4,
    "bettingAcceptance" = 5,
    "bettingPayout" = 6,
    "lotteryTicketSales" = 7,
    "lotteryPayout" = 8,
    "intellectualPropertyUsage" = 9,
    "advancePayment" = 10,
    "userCommission" = 11,
    "penaltyPayment" = 12,
    "OtherTransactionType" = 13,
    "propertyRightsTransfer" = 14,
    "nonOperatingIncome" = 15,
    "taxDeductibleExpenses" = 16,
    "tradeFeePayment" = 17,
    "resortFee" = 18,
    "pawn" = 19,
    "expenseReduction" = 20,
    "pensionInsuranceIP" = 21,
    "pensionInsuranceOrg" = 22,
    "medicalInsuranceIP" = 23,
    "medicalInsuranceOrg" = 24,
    "socialInsurance" = 25,
    "casinoTransactions" = 26,
    "bankAgentCashDisbursement" = 27,
    "exciseGoodsUnmarked" = 30,
    "exciseGoodsMarked" = 31,
    "markedGoodsUnmarked" = 32,
    "markedGoodsMarked" = 33,
}